## Instructions:

### Filters Panel and Graphs:

1. On the filters section located on the left side of the page, begin by selecting a team from the drop-down box.

2. Determine the criteria for the “Matching Characteristics” section, also located in the filters section on the left side of the page.

	a. The filters "Years After Selected Team" and " Years Before Selected Team" range from 0 to 2 years ex: a team from 2017 with a selection of 2 years before and 1 year after would allow for matching with teams from 2015 through 2018.
	
	b. The “Show Conferences” checkbox enables users to choose which conferences to be included for analysis

3. Within the visualization section of the page located beneath the lighter colored tab beginning with “Four Factors," select team names from the colored legend on the right side of the page to display specific teams within the radar chart.

4. Go through the tabs following “Four Factors” to see advanced statistics, offense, and defense-related metrics, including additional visualizations, and experience and luck analyses represented by graphs.

### Data:

1. Based on the selections made on the filters section of the “Graphs” tab previously discussed, the “Data” tab located in the horizontal grey menu bar will display statistics on the ten most similar teams, teams matching the selection criteria, and all teams.

	a. There is a drop-down box to allow editing the number of entries shown on each of these pages, as well as search bars to allow for quickly locating specific teams.

2. The “All Teams” tab allows users to change their selection criteria by dragging the start and end points buttons for years selected and range of overall ranking similar to the filtering criteria previously used on the “Graphs” tab.

## Map:

1.	Select the “Map” tab from the menu bar to view the locations of your selected team and the matched teams’ arenas visualized on a map. Hover over the location pins to see additional details regarding the team’s location, arena, ranking, record, and conference. 

## Abreviations Used:

### Four Factors:

- Opp eFG: 
  - Opponent's Effective Field Goal Percentage
- Opp TO:
  - Opponent's Turnover Percentage
- Def Reb:
  - Defensive Rebound Percentage
- Opp FT Rate:
  - Opponent's Free Throw Attempt Rate
- Off eFG:  
  - Offensive Effective Field Goal Percentage
- Off TO: 
  - Offensive Turnover Percentage
- Off Reb:
  - Offensive Rebound Percentage
- Off FT Rate:
  - Offensive Free Throw Attempt Rate

### Advanced Statistics 

- Strength of Schedule Opp D:
  - Opponent's Defensive Strength of Schedule 
- Strength of Schedule Opp O:
  - Opponent’s Offensive Strength of Schedule
- AdjO:
  - Adjusted Offensive Efficiency
- AdjD:
  - Adjusted Defensive Efficiency
-AdjT:
  - Adjusted Tempo
  
### Offense:

#### Polar Radar Chart:

- Off 3P:
  - Offensive Three-Point Percentage
- Off 2P:
  - Offensive Two-Point Percenatge
- Off FT:
  - Offensive Number of Free Throw Percentage
- Off A:
  - Offensive True Shooting Percentage
- Off 3P Attempts:
  - Offensive Three-Point Attempt Rate
- Off eFG:
  - Offensive Effective Field Goal Percentage
- Off Reb:
  - Offensive Rebounding Percentage
- Off FT Rate:
  - Offensive Free Throw Rate

#### Bar Chart:

- Off Stl:
  - Offensive Steal Rate
- Off NST:
  - Offensive Non-Steal Turnovers
- Off Blk: 
  - Offensive Block Rate
  
### Defense:

#### Polar Radar Chart:

- Opp 3P:
  - Opponent's Three-Point Percentage
- Opp 2P:
  - Opponent's Two-Point Percenatge
- Opp FT:
  - Opponent's Number of Free Throw Percentage
- Opp A:
  - Opponent's True Shooting Percentage
- Opp 3P Attempts:
  - Opponent's Three-Point Attempt Rate
- Opp eFG:
  - Opponent's Effective Field Goal Percentage
- Def Reb:
  - Defensive Rebounding Percentage
- Opp FT Rate:
  - Opponent's Free Throw Rate

#### Bar Chart:

- Def Stl:
  - Defensive Steal Rate
- Opp NST:
  - Opponent's Non-Steal Turnovers
- Def Blk: 
  - Defensive Block Rate
  
### Experience and Luck:

- Eperience:
  - How Much Experience a Team Has 
- Luck: 
  - How Lucky a Team is