ui <- (
  fluidPage(
    theme = shinytheme("sandstone"),
    navbarPage("NCAA Team Matcher",
               tabPanel("Graphs",
                        fluidRow(
                          column(2,
                                 h5(tags$b("Selected Team:"))),
                          column(2,
                                 h5(tags$b("Matched Teams:")))),
                        fluidRow(
                          column(1,
                                 uiOutput("selected_team_home")),
                          column(1,
                                 h5(" ")),
                          column(1,
                                 uiOutput("team_1_home")),
                          column(1,
                                 uiOutput("team_2_home")),
                          column(1, 
                                 uiOutput("team_3_home")),
                          column(1, 
                                 uiOutput("team_4_home")),
                          column(1,
                                 uiOutput("team_5_home")),
                          column(1, 
                                 uiOutput("team_6_home")),
                          column(1, 
                                 uiOutput("team_7_home")),
                          column(1, 
                                 uiOutput("team_8_home")),
                          column(1, 
                                 uiOutput("team_9_home")),
                          column(1, 
                                 uiOutput("team_10_home"))),
                        br(),
                        sidebarLayout(
                          sidebarPanel(width = 4,
                                       h5(tags$b("Matching Characteristics:")),
                                       selectInput("team", "Select a Team:",
                                                   unique(teams_table$Team_Year),
                                                   selectize = TRUE,
                                                   selected = "Notre Dame 2017"),
                                       selectInput("years_before",
                                                   "Years Before Selected Team:",
                                                   c(0, 1, 2)),
                                       selectInput("years_after",
                                                   "Years After Selected Team:",
                                                   c(0, 1, 2)),
                                       sliderInput("overall_rank", "Range of Overall Ranking:",
                                                   min = 1, max = 353,
                                                   value = c(1, 353)),
                                       sliderInput("height",
                                                   "Average Height:",
                                                   min = min(teams_table$Avg_Height),
                                                   max = max(teams_table$Avg_Height),
                                                   value = c(73.1, 80.1)),
                                       checkboxInput("show_conference",
                                                     strong("Show Conferences:"),
                                                     value = FALSE),
                                       conditionalPanel("input.show_conference == true",
                                                        actionButton("selectall", label="Select/Deselect all"),
                                                        checkboxGroupInput("conference", "Conferences:",
                                                                           choices=c("A10"="A10", "ACC"="ACC", "AE"="AE", "Amer"="Amer",
                                                                                     "ASun"="ASun", "B10"="B10", "B12"="B12", "BE"="BE",
                                                                                     "BSky"="BSky", "BSth"="BSth", "BW"="BW",
                                                                                     "CAA"="CAA", "CUSA"="CUSA", "GWC" ="GWC", "Horz"="Horz", "ind"="ind",
                                                                                     "Ivy"="Ivy", "MAAC"="MAAC", "MAC"="MAC", "Mcon"="Mcon", 
                                                                                     "MEAC"="MEAC", "MVC"="MVC", "MWC"="MWC", "NEC"="NEC",
                                                                                     "OVC"="OVC", "P10"="P10", "P12"="P12", "Pat"="Pat",
                                                                                     "SB"="SB", "SC"="SC", "SEC"="SEC", "Slnd"="Slnd",
                                                                                     "Sum"="Sum", "SWAC"="SWAC", "WAC"="WAC", "WCC"="WCC"),
                                                                           selected = c("A10", "ACC", "AE", "Amer", "ASun", "B10", "B12", "BE",
                                                                                        "BSky", "BSth", "BW", "CAA", "CUSA", "GWC", "Horz", "ind",
                                                                                        "Ivy", "MAAC", "MAC", "Mcon", "MEAC", "MVC", "MWC", "NEC",
                                                                                        "OVC", "P10", "P12", "Pat", "SB", "SC", "SEC", "Slnd",
                                                                                        "Sum", "SWAC", "WAC", "WCC"),
                                                                           inline=TRUE)),
                                       tags$button("Reset to Default", 
                                                   id="reset", 
                                                   type = "button", 
                                                   class="btn btn-danger action-button",
                                                   onclick="history.go(0)")),
                          mainPanel(width = 8,
                                    tabsetPanel(
                                      tabPanel("Four Factors",
                                               h3("Four Factors:"),
                                               plotlyOutput("four_factors_plot"),
                                               hr(),
                                               DT::dataTableOutput("four_factors_table")),
                                      tabPanel("Advanced Statistics",
                                               h3("Advanced Statistics:"),
                                               plotlyOutput("advanced_stats_plot"),
                                               hr(),
                                               DT::dataTableOutput("advanced_stats_table")),
                                      tabPanel("Offense",
                                               h3("Offense"),
                                               plotlyOutput("advanced_offense_plot"),
                                               hr(),
                                               plotlyOutput("offense_small_plot"),
                                               hr(),
                                               DT::dataTableOutput("offense_stats_table")),
                                      tabPanel("Defense",
                                               h3("Defense:"),
                                               plotlyOutput("defense_plot"),
                                               hr(),
                                               plotlyOutput("defense_small_plot"),
                                               hr(),
                                               DT::dataTableOutput("defense_team_table")),
                                      tabPanel("Experience And Luck",
                                               h3("Experience:"),
                                               plotlyOutput("experience_plot"),
                                               hr(),
                                               h3("Luck"),
                                               plotlyOutput("luck_plot")))))),
               tabPanel("Data",
                        tabsetPanel(
                          tabPanel("10 Similar Teams",
                                   br(),
                                   fluidRow(
                                     h3("Selected Team:"),
                                     uiOutput("selected_team")),
                                   br(),
                                   DT::dataTableOutput("selected_team_table"),
                                   hr(),
                                   h3("10 Most Similar Teams:"),
                                   fluidRow(
                                     column(1,
                                            uiOutput("team_1")),
                                     column(1, 
                                            uiOutput("team_2")),
                                     column(1, 
                                            uiOutput("team_3")),
                                     column(1,
                                            uiOutput("team_4")),
                                     column(1,
                                            uiOutput("team_5")),
                                     column(1,
                                            uiOutput("team_6")),
                                     column(1, 
                                            uiOutput("team_7")),
                                     column(1, 
                                            uiOutput("team_8")),
                                     column(1,
                                            uiOutput("team_9")),
                                     column(1, 
                                            uiOutput("team_10"))),
                                   br(),
                                   DT::dataTableOutput("match_team_table")),
                          tabPanel("Teams Matching Criteria",
                                   br(),
                                   DT::dataTableOutput("match_characteristics")),
                          tabPanel("All Teams",
                                   h3("All Teams:"),
                                   fluidRow(
                                     column(3,
                                            sliderInput("year_table", "Select Years:",
                                                        min = min(teams_table$Year),
                                                        max = max(teams_table$Year),
                                                        value = c(min(teams_table$Year),
                                                                  max(teams_table$Year)),
                                                        sep ="",
                                                        step = 1)),
                                     column(3, 
                                            sliderInput("overall_rank_table", "Range of Overall Ranking:",
                                                        min = 1, max = 353,
                                                        value = c(1, 200))),
                                     column(3, 
                                            selectInput("conference_table", "Select Conference(s):",
                                                        c("All", unique(teams_table$Conference)),
                                                        selectize = TRUE,
                                                        multiple = TRUE,
                                                        selected = "All"))),
                                   h6("Note: Overall Rank is from Ken Pomeroy's ranking"),
                                   DT::dataTableOutput("all_data_table")))),
               tabPanel("Map",
                        fluidRow(column(3, 
                                        h4("Selected Team:")),
                                 column(3, 
                                        h4("Matched Teams:"))),
                        fluidRow(column(2, 
                                        uiOutput("selected_team_map")),
                                 column(2, 
                                        uiOutput("team_1_map")),
                                 column(2,
                                        uiOutput("team_2_map")),
                                 column(2, 
                                        uiOutput("team_3_map")),
                                 column(2, 
                                        uiOutput("team_4_map")),
                                 column(2, 
                                        uiOutput("team_5_map"))),
                        br(),
                        fluidRow(
                          column(2),
                          column(2, 
                                 uiOutput("team_6_map")),
                          column(2, 
                                 uiOutput("team_7_map")),
                          column(2, 
                                 uiOutput("team_8_map")),
                          column(2, 
                                 uiOutput("team_9_map")),
                          column(2, 
                                 uiOutput("team_10_map"))),
                        br(),
                        leafletOutput("NCAA_Map")),
               tabPanel("Instructions",
                        fluidRow(
                          column(1,
                                 h4(" ")),
                          column(8, 
                                 tags$img(src="final_four.jpg", height = 500))),
                        br(),
                        includeMarkdown("https://raw.githubusercontent.com/jjenki22/KNN-NCAA-Team-Matcher/master/Instructions.Rmd"),
                        br()),
               tabPanel("About Us",
                        fluidRow(
                          column(1, 
                                 hr("")),
                          column(8, 
                                 tags$img(src="Notre Dame.jpeg", height = 500))),
                        br(),
                        includeMarkdown("https://raw.githubusercontent.com/jjenki22/KNN-NCAA-Team-Matcher/master/SportsAnalytics.rmd"),
                        br()))))